ktor:
    development:
              true
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
        watch:
         -resources
         -classes
